### ISSUE TITLE
Email subject format

### ISSUE THREAD

**Issue by redrick** [znuny/Znuny4OTRS-GIArticleSend#3]
great thing you did here, really appreciate your hard work :)

I got small thing, is not a problem, is more of a feature request...

We use this to send email through API from our employee through OTRS to customer while still keeping copy in OTRS, which is exactly what we wanted, but recently it seems customers are either bothered by the subject line or it gets filtered by their incoming filters as somehow suspicious message....

I had a look and its mainly because subject line contains Ticket ID, which customer does not necessarily  need...

I did some digging around and found this:
http://lists.otrs.org/pipermail/otrs/2009-November/029266.html

Which is exactly right and can be configured:
![ticketformat](https://user-images.githubusercontent.com/865364/28863701-4af71e02-776a-11e7-955a-ef74f48c7039.png)

But that means for us that we change this for the whole system and that would hurt internal process of using OTRS, where we work with this ID to ease the pain of searching and stuff....

Please is there any chance you would consider putting another param in for this?

Ideal case for me is as I added to request these line from this plugin:
```
ArticleSend => 1,
To          => 'email@example.com', # Email address to send article to.
```

I would also give it:
```
SubjectFormat => 'None' # Possible options 'Left', 'Right', 'None'
```

Otherwise it defaults to system setting described in:
http://lists.otrs.org/pipermail/otrs/2009-November/029266.html

Is it anywhere near possible? I am long time Ruby developer with PHP and Python experience, never done fulltime Perl, but I am willing to help if you point me in right direction :) 

Thanks a lot :)

**Comment by thorsteneckel** [comment]
Hi @redrick - Thanks! We're glad you like it. Sadly this sounds like more or less a particular case you are describing. So we currently have no plans to implement this. OTRS will not work properly on responses to that send emails. Since the TicketNumber (identifier) is missing OTRS has no clue that the received email is a follow up and will create a new Ticket - instead of detecting the source ticket and create a follow up for the sending one as it should be. There are some ways to detect this but I'd have to go in to much detail for the scope of this issue.
Please make sure this is no issue for your process and remember this change in future issue cases.

However adding this should be fairly easy - especially with the programming background you have 🚀 

I added two patches for the current master version: [Patches.zip](https://github.com/znuny/Znuny4OTRS-GIArticleSend/files/1193219/Patches.zip)

You will have to apply those changes on any package or framework update. Your package manager will tell you that there are untracked changes. So please be aware.

If you need further support or any other professional enterprise service you can always contact us via `support@znuny.com`.

Happy hacking!

**Comment by thorsteneckel** [comment]
PS: If you like to work on a RoR ticketing system we would be happy to have your support over at https://github.com/zammad/zammad 🤓 

🚀
